Add parallel Qt6 build path for Debian 13 arm64

diff --git a/functions/compile b/functions/compile
--- a/functions/compile
+++ b/functions/compile
@@ -3,9 +3,6 @@ compile(){
 ## crosstool-ng doesn't like LD_LIBRARY_PATH set
 unset LD_LIBRARY_PATH
 
-# force qt5
-export QT_SELECT=5
-
 ## Find cross-compile tools
 GCCBIN=$( ls -1d ${DIR_BUILD}/x-tools/${DSTR}/bin/*-gcc | head -n1 )
 GPPBIN=$( ls -1d ${DIR_BUILD}/x-tools/${DSTR}/bin/*-g++ | head -n1 )
@@ -38,6 +35,75 @@ esac
 
 ## Set linker path
 MLIB="${DIR_LIB}/${DSTR}"
+QT_PKGCONFIG_DIRS="${MLIB}/usr/lib/${LINARCH}/pkgconfig:${MLIB}/usr/lib/pkgconfig:${MLIB}/usr/share/pkgconfig"
+
+resolve_qt_settings() {
+  export PKG_CONFIG_SYSROOT_DIR="${MLIB}"
+  export PKG_CONFIG_LIBDIR="${QT_PKGCONFIG_DIRS}"
+  unset PKG_CONFIG_PATH
+
+  if pkg-config --exists Qt6Core Qt6Gui Qt6Widgets
+  then
+    QT_MAJOR=6
+    QT_CFLAGS=$(pkg-config --cflags Qt6Core Qt6Gui Qt6Widgets)
+    QT_LIBS=$(pkg-config --libs Qt6Core Qt6Gui Qt6Widgets)
+    if command -v qmake6 >/dev/null 2>&1
+    then
+      QT_MOC="$(qmake6 -query QT_HOST_LIBEXECS)/moc"
+    elif [ -x /usr/lib/qt6/libexec/moc ]
+    then
+      QT_MOC=/usr/lib/qt6/libexec/moc
+    else
+      echo "ERROR: Qt6 was found in ${MLIB}, but no host Qt6 moc was found"
+      exit 1
+    fi
+  elif pkg-config --exists Qt5Core Qt5Gui Qt5Widgets
+  then
+    QT_MAJOR=5
+    QT_CFLAGS=$(pkg-config --cflags Qt5Core Qt5Gui Qt5Widgets)
+    QT_LIBS=$(pkg-config --libs Qt5Core Qt5Gui Qt5Widgets)
+    QT_MOC=$(command -v moc)
+    if [ -z "${QT_MOC}" ]
+    then
+      echo "ERROR: Qt5 was found in ${MLIB}, but no host moc was found"
+      exit 1
+    fi
+  else
+    echo "ERROR: No supported Qt development package set was found in ${MLIB}"
+    echo "Checked pkg-config paths: ${QT_PKGCONFIG_DIRS}"
+    exit 1
+  fi
+}
+
+rewrite_qt_makefiles() {
+  QTMAKE="${DIR_BUILD}/src/${MAMEFORK}/build/projects/sdl/mame/gmake-linux"
+  QT_PATTERN="Qt${QT_MAJOR}Core|Qt${QT_MAJOR}Gui|Qt${QT_MAJOR}Widgets"
+
+  if [ ! -f "${QTMAKE}/qtdbg_sdl.make" ] || [ ! -f "${QTMAKE}/mame.make" ]
+  then
+    echo "ERROR: Expected generated Qt makefiles were not found in ${QTMAKE}"
+    exit 1
+  fi
+
+  echo "Rewriting generated MAME makefiles to use Qt${QT_MAJOR} from ${MLIB}"
+
+  QT_CFLAGS="${QT_CFLAGS}" perl -0pi -e 's@ -I\$\(shell qmake(?:6)? -query QT_INSTALL_HEADERS\)@$ENV{QT_CFLAGS}@g' "${QTMAKE}/qtdbg_sdl.make"
+  QT_MOC="${QT_MOC}" perl -0pi -e 's@/usr/lib/qt6/libexec/moc|/usr/lib/qt5/bin/moc|moc-qt5|moc@$ENV{QT_MOC}@g' "${QTMAKE}/qtdbg_sdl.make"
+  perl -0pi -e 's@ -L\$\(shell qmake(?:6)? -query QT_INSTALL_LIBS\)@@g' "${QTMAKE}/qtdbg_sdl.make" "${QTMAKE}/mame.make"
+  QT_LIBS="${QT_LIBS}" perl -0pi -e 's@ -lQt[56]Core -lQt[56]Gui -lQt[56]Widgets@ $ENV{QT_LIBS}@g' "${QTMAKE}/mame.make"
+
+  if ! rg -n --fixed-strings "${QT_MOC}" "${QTMAKE}/qtdbg_sdl.make" >/dev/null
+  then
+    echo "ERROR: Failed to inject the expected moc path into qtdbg_sdl.make"
+    exit 1
+  fi
+
+  if ! rg -n -e "${QT_PATTERN}" "${QTMAKE}/mame.make" >/dev/null
+  then
+    echo "ERROR: Failed to inject the expected Qt${QT_MAJOR} link libraries into mame.make"
+    exit 1
+  fi
+}
 
 echo "Preparing MAME..."
 
@@ -116,6 +182,10 @@ echo "g++ : ${GPPBIN}"
 echo "ld  : ${LDBIN}"
 echo "ar  : ${ARBIN}"
 
+resolve_qt_settings
+echo "Qt  : Qt${QT_MAJOR} from ${MLIB}"
+echo "moc : ${QT_MOC}"
+
 make clean
 
   # 1) Build host tools (genie) with host compiler
@@ -126,6 +196,8 @@ make clean
     PLATFORM=${MAMEPLATFORM} \
     TARGETOS=linux \
     -j${CPUS}
+
+  rewrite_qt_makefiles
 
   # 2) Build MAME for target with cross toolchain
   make \
